const {test,expect}=require('@playwright/test');
test('Gemini recent row keeps the icon inline and deletes only checked native IDs',async({page,context},testInfo)=>{
 const ids=['943f5c7602a67cc4','519f8a59c0ccc47e'];const writes=[];const preparations=[];
 const html=`<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="og-profile-acct" content="fixture@example.test"><script>var config={"SNlM0e":"fixture-token","cfb2h":"build","FdrFJe":"sid"}</script><style>side-navigation-content{display:block;width:300px}a{display:flex;padding:8px}.expandable-section-header-row{display:flex}button{font:inherit}</style><main><side-navigation-content><div class="expandable-section-header-row"><button aria-controls="sidenav-section-content-chats">最近</button></div><div id="sidenav-section-content-chats"><conversations-list>${ids.map((id,i)=>`<gem-nav-list-item data-test-id="conversation"><a href="/app/${id}" aria-label="Fixture ${i}"><span>Fixture ${i}</span></a></gem-nav-list-item>`).join('')}</conversations-list></div></side-navigation-content><article><a href="/app/abcdef">Not sidebar</a></article></main>`;
 await context.route('https://gemini.google.com/**',async route=>{if(new URL(route.request().url()).searchParams.has('authuser')&&route.request().method()==='GET'){preparations.push(route.request().url());return route.fulfill({status:302,headers:{location:'https://gemini.google.com/app'}});}if(route.request().method()==='POST'){writes.push(JSON.parse(new URLSearchParams(route.request().postData()).get('f.req')));return route.fulfill({body:")]}'\n42\n"+JSON.stringify([['wrb.fr','GzXR5e','[]',null,null,null,'generic']])});}return route.fulfill({contentType:'text/html',body:html});});
 await page.goto('https://gemini.google.com/app');await page.evaluate(()=>{globalThis.browser={storage:{local:{get:async d=>({...d,language:'en',checkboxMode:'always'}),set:async()=>{}},onChanged:{addListener(){}}},runtime:{id:'test',onMessage:{addListener(){}}}};globalThis.chrome=globalThis.browser;});
 for(const f of ['core','gemini','batch','i18n','archive','bots','content'])await page.addScriptTag({path:'src/'+f+'.js'});await page.addStyleTag({path:'src/content.css'});
 await expect(page.locator('.cs-checkbox')).toHaveCount(2);await expect(page.locator('article .cs-checkbox')).toHaveCount(0);const row=page.locator('.expandable-section-header-row');await expect(row.locator('.cs-toggle')).toBeVisible();const a=await row.locator('button').first().boundingBox(),b=await row.locator('.cs-toggle').boundingBox();expect(Math.abs(a.y+a.height/2-b.y-b.height/2)).toBeLessThan(2);
 await page.screenshot({path:testInfo.outputPath('gemini-recent.png')});await page.locator('.cs-checkbox').first().check();await page.locator('.cs-toggle').click();await expect(page.locator('[data-cs-action="archive"]')).toHaveCount(0);await page.locator('[data-cs-action="delete"]').click();expect(writes).toEqual([]);await page.locator('.cs-confirm .cs-danger').click();await expect.poll(()=>writes.length).toBe(1);expect(preparations).toEqual([]);expect(writes[0]).toEqual([[['GzXR5e','["c_'+ids[0]+'"]',null,'generic']]]);await expect(page.locator('a[href="/app/'+ids[0]+'"]')).toBeHidden();await expect(page.locator('a[href="/app/'+ids[1]+'"]')).toBeVisible();
});
