const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const languages = {'zh-CN':'简体中文','zh-TW':'繁體中文',en:'English',fr:'Français',ja:'日本語',ru:'Русский'};
const catalogs = Object.fromEntries(Object.keys(languages).map(lang => [lang, JSON.parse(fs.readFileSync(path.join(root, '_locales', lang.replace('-', '_'), 'messages.json'), 'utf8'))]));
for (const [lang, catalog] of Object.entries(catalogs)) {
  for (const [key, base] of Object.entries(catalogs.en)) {
    const entry = catalog[key];
    if (!entry?.message) throw new Error(`${lang}: missing ${key}`);
    const placeholders = value => Object.keys(value.placeholders || {}).sort().join(',');
    if (placeholders(entry) !== placeholders(base)) throw new Error(`${lang}: mismatched placeholders in ${key}`);
    // Store limits on the manifest strings: Safari rejects descriptions over 112 characters (App Store export error 90862); Chrome allows 132 and names up to 45.
    if (key === 'extensionDescription' && [...entry.message].length > 112) throw new Error(`${lang}: extensionDescription has ${[...entry.message].length} characters; Safari allows at most 112`);
    if (key === 'extensionName' && [...entry.message].length > 45) throw new Error(`${lang}: extensionName has ${[...entry.message].length} characters; the stores allow at most 45`);
    for (const match of entry.message.matchAll(/\$([A-Za-z_]+)\$/g)) {
      if (!entry.placeholders?.[match[1].toLowerCase()]) throw new Error(`${lang}: undefined placeholder ${match[1]}`);
    }
  }
}
const output = `// Generated by scripts/build-i18n.cjs from _locales. Do not edit directly.
globalThis.ChatTidyI18n = (() => {
  const languages = ${JSON.stringify(languages)};
  const catalogs = ${JSON.stringify(catalogs)};
  function normalize(lang = '') {
    const value = String(lang).replace(/_/g, '-').toLowerCase();
    if (/^zh-(tw|hk|mo|hant)(-|$)/.test(value)) return 'zh-TW';
    if (/^zh(-|$)/.test(value)) return 'zh-CN';
    return languages[value.split('-')[0]] ? value.split('-')[0] : 'en';
  }
  let nativeAvailable=true;
  let cachedLanguage;
  function browserLanguage() {
    if(cachedLanguage)return cachedLanguage;
    let language=globalThis.navigator?.language || 'en';
    try{language=globalThis.chrome?.i18n?.getUILanguage?.() || language;}catch{nativeAvailable=false;}
    return cachedLanguage=normalize(language);
  }
  const dict = Object.fromEntries(Object.entries(catalogs).map(([lang, messages]) => [lang,
    Object.fromEntries(Object.entries(messages).map(([key, entry]) => [key,
      entry.message.replace(/\\$([A-Za-z_]+)\\$/g, (_, name) => '{' + name.toLowerCase() + '}')]))]));
  function t(lang, key, vars = {}) {
    const locale = normalize(lang);
    const entry = catalogs[locale][key] || catalogs.en[key];
    if (!entry) return key;
    // Chrome uses the browser locale; the bundled catalogs preserve manual language switching.
    const browserLocale=browserLanguage();
    try {
    const native = nativeAvailable && globalThis.chrome?.i18n;
    if (native?.getMessage && locale === browserLocale) {
      const substitutions = [];
      for (const [name, placeholder] of Object.entries(entry.placeholders || {})) {
        substitutions[Number(placeholder.content.slice(1)) - 1] = String(vars[name] ?? '');
      }
      const message = native.getMessage(key, substitutions);
      if (message) return message;
    }
    }catch{nativeAvailable=false;}
    return (dict[locale][key] || dict.en[key]).replace(/\\{(\\w+)\\}/g, (_, name) => String(vars[name] ?? ''));
  }
  return {languages, dict, normalize, browserLanguage, t};
})();
`;
const target = path.join(root, 'src/i18n.js');
if (process.argv.includes('--check')) {
  if (fs.readFileSync(target, 'utf8') !== output) throw new Error('Run npm run build:i18n to update the language bundle.');
} else fs.writeFileSync(target, output);
